version: "3.7"
services:
  rabbit:
    image: rabbitmq:latest

  fastapi:
    image: celery_simple:latest
    ports:
      - 8080:8080
    entrypoint: uvicorn app:app --host 0.0.0.0 --port 8080

  worker:
    image: celery_simple:latest
    entrypoint: celery worker --app=worker.celery_app -c 2 --loglevel=info
